Feature 112: Final-form for Boilers
JoseBlois/rr-caldar-frontend pull request #22
Opened 2021-01-14 01:59 UTC by ValentinSilvestri

Final form finally added to Boilers.

2021-01-14 13:00 UTC, lmalvasia requested changes

2021-01-14 13:00 UTC, lmalvasia commented on src/components/Boilers/BoilersForm/index.js
> +                  <div>
You can use the shared component `SelectInput`

2021-01-15 02:28 UTC, ValentinSilvestri commented on src/components/Boilers/BoilersForm/index.js
> +                  <div>
Done.

2021-01-15 02:28 UTC, ValentinSilvestri commented on src/components/Boilers/BoilersForm/index.js
> +                  <div>
Done.

2021-01-15 02:28 UTC, ValentinSilvestri commented on src/components/Boilers/BoilersForm/index.js
> +  const required = (value) => (value ? undefined : 'Required');
Done.

2021-01-15 02:29 UTC, ValentinSilvestri commented on src/components/Boilers/BoilersForm/index.js
> +  const [boilerTypeOptions, setBoilerTypeOptions] = useState([]);
Done.

2021-01-15 02:30 UTC, ValentinSilvestri commented on src/components/Boilers/BoilersForm/index.js
> +  useEffect(async () => {
Partially done, got some issues with the select and the update.

2021-01-15 03:32 UTC, lmalvasia approved these changes

2021-01-15 04:46 UTC, merged